# Generated by Django 4.1 on 2026-02-07 06:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("provider_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="district",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name="customuser",
            name="father_name",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name="customuser",
            name="mother_name",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name="customuser",
            name="village",
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
