# Generated by Django 4.1 on 2026-02-07 07:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("provider_app", "0002_customuser_district_customuser_father_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="phone",
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="password",
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
