# Generated by Django 4.1 on 2026-02-08 08:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("provider_app", "0003_customuser_phone_alter_customuser_password"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="image",
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
