# Generated by Django 4.1 on 2026-02-08 08:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("provider_app", "0004_customuser_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="profile_images/"),
        ),
    ]
