# Generated by Django 4.1 on 2026-02-09 06:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("provider_app", "0005_alter_customuser_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="SliderList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="slider_images/"
                    ),
                ),
                ("rank", models.IntegerField(default=0)),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "slider_list",
            },
        ),
    ]
