# Generated by Django 4.1 on 2026-02-10 02:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("provider_app", "0006_sliderlist"),
    ]

    operations = [
        migrations.CreateModel(
            name="Services",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category_title", models.CharField(max_length=100)),
                ("service_title", models.CharField(max_length=150)),
                ("service_details", models.TextField()),
                ("rank", models.IntegerField(default=0)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="service_images/"
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "service_list",
                "ordering": ["rank"],
            },
        ),
    ]
