# Generated by Django 4.1 on 2026-02-15 10:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("provider_app", "0007_services"),
    ]

    operations = [
        migrations.AddField(
            model_name="services",
            name="price",
            field=models.IntegerField(default=0),
        ),
    ]
